# docker-compose up --build

version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    environment:
      - ENV_FILE_PATH=/app/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
