name: CI/CD Test and Build Pipeline

on:
  push:
    branches:
      - main # Run on pushes to the main branch

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: |
          cd backend
          go mod download

      - name: Run Unit Tests
        run: |
          cd backend
          go test ./... -v

 docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [backend-tests] # Save resources and only run this job if tests pass

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Backend Image
      run: docker build -t petersb/backend:latest ./backend

    - name: Build Frontend Image
      run: docker build -t petersb/frontend:latest ./frontend

    - name: Push Backend Image
      run: docker push petersb/backend:latest

    - name: Push Frontend Image
      run: docker push petersb/frontend:latest