name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Run on pushes to the main branch

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test ./... -v
